### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by krokofant**
* Changed postinstall so it won't brake on Windows
* No need to run test and build upon install
* Removed bower
* Removed jasmine-moar-matchers dep

grunt test seems broken on local, I'm not sure why. It says:
> Registering "grunt-karma" local Npm module tasks.
Reading D:\GitHub\ngImageInputWithPreview\node_modules\grunt-karma\package.json...OK
Parsing D:\GitHub\ngImageInputWithPreview\node_modules\grunt-karma\package.json...OK
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>>     at Object.<anonymous> (D:\GitHub\ngImageInputWithPreview\node_modules\socket.io\lib\store.js:35:42)
>>     at Module._compile (module.js:652:30)
>>     at Object.Module._extensions..js (module.js:663:10)
>>     at Module.load (module.js:565:32)
>>     at tryModuleLoad (module.js:505:12)
>>     at Function.Module._load (module.js:497:3)
>>     at Module.require (module.js:596:17)
>>     at require (internal/module.js:11:18)
>>     at Object.<anonymous> (D:\GitHub\ngImageInputWithPreview\node_modules\socket.io\lib\manager.js:16:13)
>>     at Module._compile (module.js:652:30)

### CODE REVIEW

**Comment by krokofant** [comment]
Now tests are passing!

@deiwin : How does this look?

**Comment by deiwin** [comment]
Looks good, thank you! I'll do some quick local sanity checks before merging, but it's great getting rid of bower :)

**Comment by deiwin** [comment]
Seems to work. At least with node version 0.10.x. I'll merge, but I'll add some other changes to make the demo work locally and to bump the version as well. Thanks again!

**Comment by deiwin** [comment]
Published as 0.1.0

**Pull request merged**
